package com.glueframework.complier;


import java.sql.SQLException;
import java.util.List;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;
import org.h2.jdbcx.JdbcDataSource;

import com.glueframework.log.ILogger;
import com.glueframework.log.LogMSG;

public class TestDbutils {
	private static ILogger logger = LogMSG.getLogger();
	public static void main(String[] args) throws Exception {
		// Create a ResultSetHandler implementation to convert the
		// first row into an Object[].
		/*ResultSetHandler<Object[]> h = new ResultSetHandler<Object[]>() {
		    public Object[] handle(ResultSet rs) throws SQLException {
		        if (!rs.next()) {
		            return null;
		        }
		    
		        ResultSetMetaData meta = rs.getMetaData();
		        int cols = meta.getColumnCount();
		        Object[] result = new Object[cols];

		        for (int i = 0; i < cols; i++) {
		            result[i] = rs.getObject(i + 1);
		        }

		        return result;
		    }
		};
		/*
		QueryRunner run = new QueryRunner();
		String urlString="jdbc:h2:D:/springboot/h2/test";
		String usernameString="admin";
		String password="";
		Connection connection=null;
      try {
		Class.forName("org.h2.Driver");
		connection=DriverManager.getConnection(urlString, usernameString, password);
	} catch (ClassNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}*/
      
		JdbcDataSource ds = new JdbcDataSource();
		 ds.setURL("jdbc:h2:D:/springboot/h2/test");
		 ds.setUser("admin");
		 ds.setPassword("");
		 QueryRunner run = new QueryRunner(ds);
//		 run.execute("create ? ..");
		 
		// Use the BeanListHandler implementation to convert all
		// ResultSet rows into a List of Test JavaBeans.
		ResultSetHandler<List<Test>> h = new BeanListHandler<Test>(Test.class);

		// Execute the SQL statement and return the results in a List of
		// Test objects generated by the BeanListHandler.
		List<Test> Tests = run.query("SELECT * FROM test", h);
		for(Test test:Tests)
			logger.debug(test.getName()+"-->"+test.getId());
		// open a connection
		/*
				try{
					 Object[] result = run.query(
							 connection, "SELECT * FROM test WHERE name=?", h, "World");
					 logger.info(result.toString());
				    // do something with the result
				} finally {
				    // Use this helper method so we don't have to check for null
				    DbUtils.close(connection);  
				}
				*/
				
	}
	@org.junit.Test
	public void fomat() throws Exception{
		QueryRunner run = new QueryRunner();
		System.out.println(String.format("create table %s fsfdsfs ", "testTable"));
		 run.execute(String.format("create table %s fsfdsfs (     )",  "testTable" ,"vcxzv"));
		 run.execute(String.format("create table %s fsfdsfs ", "testTable"), "");
	}   
	
	 
}
